global:
  resolve_timeout: 5m

templates:
  - '/etc/alertmanager/*.tmpl'

route:
  receiver: 'discord-geral'
  group_by: ['alertname', 'instance']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1m

receivers:
  - name: 'discord-geral'
    discord_configs:
      - webhook_url: 'https://discord.com/api/webhooks/1422602417911894197/-WIVgGuvVJ3YnluYWjAufZnyJVxtOXgzxln1sJ_8g9hTFCIrqIsHIulkeoYkBFMfeFIv'
        send_resolved: true
        title: '{{ template "alert_title" . }}'
        message: '{{ template "discord.message" . }}'



